### ISSUE TITLE
gtk/gtk.h: No such file or directory    48 | #include <gtk/gtk.h>

### ISSUE THREAD

**Issue by ghost** [ohwgiles/epoccam_linux#10]
`Package gtk+-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-2.0' found
Package gtk+-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-2.0' found
gcc -DPREFIX=\"/usr\" -Wall -std=c99 -g  -o epoccam epoccam_linux.c 
epoccam_linux.c:48:10: fatal error: gtk/gtk.h: No such file or directory
   48 | #include <gtk/gtk.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:9: epoccam] Error 1`
I have this problem

**Comment by ohwgiles** [comment]
Probably you need to install your distribution's development packages for GTK2. On most Ubuntu/Debian systems this is `libgtk2.0-dev`.

**Comment by vbxx3** [comment]
You can find possible pathes with this command:
`echo $(pkg-config --variable pc_path pkg-config)${PKG_CONFIG_PATH:+:}${PKG_CONFIG_PATH}`
and exporting `export PKG_CONFIG_PATH=YOUR_RESULT`

Also, it may be not installed at all.
`sudo apt-get install gtk+2.0`
