### ISSUE TITLE
No tray icon

### ISSUE THREAD

**Issue by jangxx** [ohwgiles/epoccam_linux#3]
When I start the program and then the iPhone app I get this output:

```
Received 2 video sizes
Offered video size: 1280x720 H264 at 30,000000fps
Offered video size: 640x480 H264 at 30,000000fps
Selection option 0
Received 0 audio options
Use the tray icon to start streaming
```

The only problem is: There's no try icon and the app just says 'Searching the network'.
Is there something else I have to do besides simply typing `./epoccam` in a terminal?

I'm running on Linux Mint MATE 17.2.

**Comment by jangxx** [comment]
Got it to work. Had to `make install` the program first.

**Comment by farhanmubasher** [comment]
I'm having same problem..

Received 1 video sizes
Offered video size: 640x480 H264 at 30.000000fps
Selection option 0
Received 0 audio options
Use the tray icon to start streaming


I have tried "make install" before "./epoccam" but still getting same error. Can you please help me with this?

**Comment by jangxx** [comment]
This was more than two years ago, I have not used Epoccam since and also reinstalled my computer at least once. I'm sorry, but I really have no idea how I could help you.

**Comment by ohwgiles** [comment]
It seems that recent versions of Ubuntu (or maybe GNOME) don't support old-fashioned gtk system tray icons. Another user worked around the issue [like this](https://github.com/ohwgiles/epoccam_linux/issues/2#issuecomment-146129698)
